name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: make
      run: cd src
      run: make
    - name: make test
      run: cd src
      run: make test
    - name: make clean
      run: cd src
      run: make clean
